name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

env:
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  compare-versions-and-schemas:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fetch master branch and get version
        run: |
          echo "Master branch version from pom.xml:"
          master_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Master branch version: $master_version"
          echo "Contents of master branch schema-variables.yml:"
          cat .github/workflows/build-deploy-image/schemas_versions.yml
          master_schema_variables=$(cat .github/workflows/build-deploy-image/schemas_versions.yml)

      - name: Checkout merge commit
        uses: actions/checkout@v2

      - name: Compare Versions and Schemas
        run: |
          echo "Feature branch version from pom.xml:"
          feature_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Feature branch version: $feature_version"
          echo "Contents of feature branch schema-variables.yml:"
          cat .github/workflows/build-deploy-image/schemas_versions.yml
          feature_schema_variables=$(cat .github/workflows/build-deploy-image/schemas_versions.yml)
          
          echo "Comparing project versions..."
          echo "Master version string length: ${#master_version}"
          echo "Feature version string length: ${#feature_version}"
          declare -p master_version feature_version
          
          echo "Comparing project versions..."
          if [ "$master_version" == "$feature_version" ]; then
              echo "Project version is unchanged"
              VERSION_CHANGED=false
          else
              echo "Project version has changed"
              VERSION_CHANGED=true
          fi
          
          echo "Comparing schema files..."
          if diff -q <(echo "$master_schema_variables") <(echo "$feature_schema_variables") > /dev/null; then
              echo "No changes in schema-variables.yml"
              SCHEMA_CHANGED=false
          else
              echo "Changes detected in schema-variables.yml"
              SCHEMA_CHANGED=true
          fi
          
          if [ "$SCHEMA_CHANGED" = true ] && [ "$VERSION_CHANGED" = false ]; then
              echo "ERROR: Schema files are different but project version is unchanged. Please increment the project version before merging."
              exit 1
          fi

  deploy-jar-if-schema-changed:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: compare-versions-and-schemas

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/master'

      - name: Deploy JAR if Schema Changed
        run: |
          echo "Contents of master branch schema-variables.yml after merge:"
          cat .github/workflows/build-deploy-image/schemas_versions.yml
          master_schema_variables=$(cat .github/workflows/build-deploy-image/schemas_versions.yml)

          echo "Checking out the merged commit SHA to get the feature branch version..."
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }} -- .github/workflows/build-deploy-image/schemas_versions.yml
          echo "Contents of feature branch schema-variables.yml after merge:"
          cat .github/workflows/build-deploy-image/schemas_versions.yml
          feature_schema_variables=$(cat .github/workflows/build-deploy-image/schemas_versions.yml)

          echo "Comparing schema files..."
          if diff -q <(echo "$master_schema_variables") <(echo "$feature_schema_variables") > /dev/null; then
              echo "No changes in schema-variables.yml"
              DTO_CHANGED=false
          else
              echo "Changes detected in schema-variables.yml"
              DTO_CHANGED=true
          fi

          if [ "$DTO_CHANGED" = true ]; then
              # Your logic for deploying the JAR
              echo "Deploying JAR since schema has changed..."
              # Remember to add the actual steps for building and deploying your JAR file
          fi
